version: "3.4"
services:
  builder:
    image: ignaciovizzo/puma:latest
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
      target: builder
  apps:
    image: ignaciovizzo/puma_apps:latest
    build:
      context: .
      dockerfile: docker/apps/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    working_dir: /apps
    volumes:
      - ./apps/:/apps:rw
      - ${DATASETS}:/data:ro
