# ICP params
threshold: 1.0
method: p2l
warm_start: true
acc_frame_count: 30
loss: huber

# Processing
downsample: true
normals: range_image # none, kdtree
voxel_size: 0.25
max_nn: 20
W: 1024
H: 64

# misc
out_dir: results/
debug: false
